### PR TITLE
Deprecate testing module

### PR DESCRIPTION
**Pull request by VenelinMartinov**
Addresses https://github.com/pulumi/pulumi-terraform-bridge/issues/1604

The module has been moved to https://github.com/pulumi/providertest/tree/main/replay

### CODE REVIEW

**Comment by t0yv0** [comment]
Might need a little more changes like https://github.com/pulumi/pulumi-terraform-bridge/pull/1638 since I've changed Errors from *string to []string.

**Comment by iwahbe** [comment]
Bumping the required go version to go1.21.0 requires bumping the installed go version:
```
Found in cache @ /opt/hostedtoolcache/go/1.20.12/x64
```

**Comment by VenelinMartinov** [comment]
providertest seems to require go 1.21 - is upgrading the go version in the bridge a concern?

**Comment by t0yv0** [comment]
We could upgrade Go in a separate PR possibly. Fraser mentioned it is getting old .

**Review by iwahbe — APPROVED** [review]
LGTM

**Pull request merged**
