### PR TITLE
Switch C# gen to schema

### PR DESCRIPTION
**Pull request by mikhailshilkov**
C# code gen is now based on the schema definition

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
@stack72 We want to take this to the next beta version of all providers

**Comment by mikhailshilkov** [comment]
@stack72 hmm, indeed. Any ideas what to look for?

**Comment by stack72** [comment]
I'll take a look for you and see what I can find

**Comment by stack72** [comment]
it just needed a make ensure to tidy the imports :)

**Pull request merged**
