### PR TITLE
Make computed outputs optional

### PR DESCRIPTION
**Pull request by VenelinMartinov**
Changes to address https://github.com/pulumi/pulumi-terraform-bridge/issues/1239

Not sure if it does the right thing though. I ran it for `pulumi-oci` and it produced a 100k line diff in the schema, essentially removing all required outputs.

`pulumi-oci` results here https://github.com/pulumi/pulumi-oci/pull/264

### CODE REVIEW

**Comment by t0yv0** [comment]
Can you make a PR against AWS? This is definitely something we need to surface and discuss before shipping as it ends up being a breaking change. It's the right thing from type safety POV but since it is breaking we might decide to either not ship it or ship it in major releases only.

**Comment by t0yv0** [comment]
A Computed+Optional property can be set by either the program or the TF provider. If left unset by
the program, but there is a custom default, presumably Pulumi will set the default as if the program
set it before passing down to TF. In that case, if the provider does not modify it to nil it out
(sounds possible but should be rare), it should indeed never be nil.

On the other hand, a Computed property can only be set by the TF provider. I believe the custom
default cannot apply to it (may be worth checking). In this case the provider is supposed to set
this property, but it can set it to a nil value. In my understanding this can be nil commonly, but I
do not have a statistic here... somehow currently this is marked as required.

**Comment by t0yv0** [comment]
It sounds like currently we model these types as non-optional which means it's not fully type-safe in some languages, like you can get nils or empty values pushed through into the result type. However if we take this change it will break the SDKs and make the types optional, as in `Foo?` in TypeScript, necessitating more nil checks in user programs. More type safety but less convenience and a breaking change. 

Something worth deliberating.

**Comment by VenelinMartinov** [comment]
In AWS for example, this change makes the URN property on all objects optional = (
Seems like quite a big change.

**Comment by VenelinMartinov** [comment]
Here is the AWS diff https://github.com/pulumi/pulumi-aws/pull/3013

**Comment by t0yv0** [comment]
That sounds like a bug in the PR then. URN property is not even a Terraform-mapped property. Why is it changing?

**Comment by VenelinMartinov** [comment]
@t0yv0 helped me realise it is not the URN which is now marked optional but the ARN in the AWS provider.

**Pull request closed without merging**
