### PR TITLE
Check that we don't already have a valid array

### LINKED ISSUE #722: Consecutive Pulumi Preview Runs on the Same Stack Return Different Update Plans
When running `pulumi preview` consecutively on the same stack, Pulumi is returning different update plans for the same stack. Note, no actual deployment (pulumi up) is occurring during `preview` runs.

Details to come, but the Pulumi Program contains an EKS cluster, K8s resources, and outputted kubeconfig.

Some sample results:
first `preview`
```
    logger.go:34:         + 28 to create
    logger.go:34:         ~ 6 to update
    logger.go:34:         +-4 to replace
```

second `preview`
```
logger.go:34:         + 28 to create
logger.go:34:         ~ 8 to update
logger.go:34:         +-24 to replace
```

The second update plan (with more updates and replacements) appears to be connected to a (possibly non-existent) change in the kubeconfig. It also appears to be connected to the k8s provider requiring an update.

Sample output from the first `preview`
```
  logger.go:34:                 ~ pulumi:providers:kubernetes: (update)
    logger.go:34:                     [id=98d63474-f87c-49ea-afb8-03445afacfdf]
    logger.go:34:                     [urn=urn:pulumi:phil-test::aws-eks::cloud:aws:eks/cluster:Cluster$pulumi:providers:kubernetes::eks-eks-k8s]
    logger.go:34:                   ~ enableServerSideApply: false => true
    logger.go:34:                   ~ version              : "3.20.1" => "3.22.1"``
```

Sample output from the second `preview` when all resources dependent on the provider are to be replaced
```
logger.go:34:                 +-pulumi:providers:kubernetes: (replace)
    logger.go:34:                     [id=98d63474-f87c-49ea-afb8-03445afacfdf]
    logger.go:34:                     [urn=urn:pulumi:phil-test::aws-eks-typescript::cloud:aws:eks/cluster:Cluster$pulumi:providers:kubernetes::eks-eks-k8s]
    logger.go:34:                     enableConfigMapMutable     : false
    logger.go:34:                     enableDryRun               : false
    logger.go:34:                     enableReplaceCRD           : false
    logger.go:34:                   ~ enableServerSideApply      : false => true
    logger.go:34:                   ~ kubeconfig                 : (json) {
    logger.go:34:                       - apiVersion     : "v1"
    logger.go:34:                       - clusters       : [
    logger.go:34:                       -     [0]: {
    logger.go:34:                               - cluster: {
    logger.go:34:                                   - certificate-authority-data: “redacted”
    logger.go:34:                                   - server                    : "https://0ea973621185408cb9b68e9e21a5ac5a.gr7.us-west-2.eks.amazonaws.com/"
    logger.go:34:                                 }
    logger.go:34:                               - name   : "kubernetes"
    logger.go:34:                             }
    logger.go:34:                         ]
    logger.go:34:                       - contexts       : [
    logger.go:34:                       -     [0]: {
    logger.go:34:                               - context: {
    logger.go:34:                                   - cluster: "kubernetes"
    logger.go:34:                                   - user   : "aws"
    logger.go:34:                                 }
    logger.go:34:                               - name   : "aws"
    logger.go:34:                             }
    logger.go:34:                         ]
    logger.go:34:                       - current-context: "aws"
    logger.go:34:                       - kind           : "Config"
    logger.go:34:                       - users          : [
    logger.go:34:                       -     [0]: {
    logger.go:34:                               - name: "aws"
    logger.go:34:                               - user: {
    logger.go:34:                                   - exec: {
    logger.go:34:                                       - apiVersion: "client.authentication.k8s.io/v1beta1"
    logger.go:34:                                       - args      : [
    logger.go:34:                                       -     [0]: "eks"
    logger.go:34:                                       -     [1]: "get-token"
    logger.go:34:                                       -     [2]: "--cluster-name"
    logger.go:34:                                       -     [3]: "eks-cluster-7c1e5ec"
    logger.go:34:                                         ]
    logger.go:34:                                       - command   : "aws"
    logger.go:34:                                       - env       : [
    logger.go:34:                                       -     [0]: {
    logger.go:34:                                               - name : "AWS_PROFILE"
    logger.go:34:                                               - value: "test"
    logger.go:34:                                             }
    logger.go:34:                                       -     [1]: {
    logger.go:34:                                               - name : "KUBERNETES_EXEC_INFO"
    logger.go:34:                                               - value: "client.authentication.k8s.io/v1beta1"
    logger.go:34:                                             }
    logger.go:34:                                         ]
    logger.go:34:                                     }
    logger.go:34:                                 }
    logger.go:34:                             }
    logger.go:34:                         ]
    logger.go:34:                     }
    logger.go:34:      => output<string>
```

### PR DESCRIPTION
**Pull request by iwahbe**
This seems to fix #722 and https://github.com/pulumi/pulumi-eks/issues/851. I'm unable to write a test, nor offer a comprehensive explanation on why this is a fix.

### CODE REVIEW

**Comment by iwahbe** [comment]
I would be super curious to hear theories on why this works.

**Comment by t0yv0** [comment]
Can you publish a repro please?

**Comment by iwahbe** [comment]
Repro was linked from the eke issue: https://github.com/pulumi/pulumi-eks/issues/851#issuecomment-1409092851.

**Comment by iwahbe** [comment]
Closed in favor of root cause fix of #774.

**Pull request closed without merging**
