### PR TITLE
Allow missing properties in PCL codegen.

### PR DESCRIPTION
**Pull request by pgavlin**
Just what it says on the tin. These changes will help ensure that
examples are not lost if and when typechecking of resource input
properties is enabled.

### CODE REVIEW

**Comment by pgavlin** [comment]
Depends on https://github.com/pulumi/pulumi/pull/7297.

**Review by lblackstone — APPROVED** [review]
Change LGTM, but didn't look into test failures

**Comment by pgavlin** [comment]
> Change LGTM, but didn't look into test failures

Test failures should be build failures, b/c these changes use an option that doesn't exist yet :)

**Comment by pgavlin** [comment]
Downstream tests are failing b/c the jobs do not run `go mod tidy`. Diffs look good locally.

**Pull request merged**
