### PR TITLE
Gofumpt the codebase

### PR DESCRIPTION
**Pull request by mikhailshilkov**
While working on another PR, I got a CI error that my file wan't gofumpt-ed. So I ran `gofumpt -w .`... and got a bunch of changes below. They look like good changes, so I'm opening this PR to apply them. Not sure why they weren't flagged before?

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
These all look like changes to deprecated, ignored and vendored folders. We have a golangci-lint configuration to ignore these, I imagine that's why we do not flag them up in CI.

You can run the linter with `make lint` or `make lint_fix`, that should not show any false positives: https://github.com/pulumi/pulumi-terraform-bridge/blob/1aa2e6420f6cc69388564e976b45a912711f0b68/Makefile#L24

**Comment by mikhailshilkov** [comment]
@VenelinMartinov Thank you for the explanation. `make lint` fails horribly on my machine with hundreds of errors, so I thought I'd run `gofump` directly, it wasn't obvious that I shouldn't. I guess I need to figure out the reason for `make lint` failures now. Happy to close the PR, I think `tf2pulumi` is effectively deprecated too.

**Review by t0yv0 — APPROVED** [review]
To make it stick a CI check is needed as well to make sure this stays consistent.

**Comment by mikhailshilkov** [comment]
I made `make lint` work by updating the the right version of `golangci-lint`. So let's stick with `make lint` as the source of truth.

**Pull request closed without merging**
