### PR TITLE
Preserve unknowns during provider preview.

### PR DESCRIPTION
**Pull request by pgavlin**
Just what it says on the tin.

### CODE REVIEW

**Comment by pgavlin** [comment]
Fixes https://github.com/pulumi/pulumi/issues/5864.

I'm working on tests to verify that we don't regress this.

**Review by leezen — APPROVED** [review]

**Comment by lukehoban** [comment]
> Just what it says on the tin.

Would love more details on what the issue was, what the design is, why these changes are the right delta to achieve the design, and what follow-ups (if any) we should consider in this area.

**Comment by leezen** [comment]
Should be noted that this is looking to address https://github.com/pulumi/pulumi/issues/5864

**Comment by pgavlin** [comment]
> > Just what it says on the tin.
> Would love more details on what the issue was, what the design is, why these changes are the right delta to achieve the design, and what follow-ups (if any) we should consider in this area.

Definitely--much of this got dropped when I squashed.

The issue was that we were not setting the `KeepUnknowns` flag in `MarshalOptions` when returning results from the provider's `Create` and `Update` operations. This caused the marshaler to omit nested unknowns. These unknowns were present in the property bags that were being marshaled, so the only delta necessary to fix this was to set this flag. I do not believe that we need much in the way of follow-up aside from more comprehensive testing in this repository for the various operations for which a provider is responsible.

**Pull request merged**
