### PR TITLE
Remove non PRC tests

### PR DESCRIPTION
**Pull request by VenelinMartinov**
We have rolled PRC out everywhere, no need to test non-PRC anymore

### CODE REVIEW

**Comment by iwahbe** [comment]
Have we removed all the non-PRC code from the bridge?

**Review by iwahbe — COMMENTED** [review]
Have we removed all the non-PRC code from the bridge?

If we have, then great. If not, I think we should wait until we remove non-PRC code before removing it's tests.

**Review by t0yv0 — APPROVED** [review]

**Comment by iwahbe** [comment]
Also, it doesn't look like we have rolled it out everywhere:

https://github.com/pulumi/pulumi-fastly/blob/6f18accf90b35730fef8285e9c4a239de3bccefb/provider/resources.go#L75-L78

If `shimv2.WithPlanResourceChange` doesn't do anything anymore, then please add a comment to the option that explains that (like `shimv2.WithDiffStrategy`):

https://github.com/pulumi/pulumi-terraform-bridge/blob/f0919962932be8de529169e4974e09552c8002b4/pkg/tfshim/sdk-v2/provider_options.go#L62-L68

**Comment by VenelinMartinov** [comment]
superseded by https://github.com/pulumi/pulumi-terraform-bridge/pull/2594

**Pull request closed without merging**
