### PR TITLE
Add ctx to CheckConfig

### PR DESCRIPTION
**Pull request by iwahbe**

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Does logging not work without that?

**Comment by iwahbe** [comment]
> Does logging not work without that?

It depends on how logging is used, but in general no.

**Comment by iwahbe** [comment]
> This looks good! Bad merge or somehow slipped through? I thought this stanza should've been on every method.

I thought so too, but it looks like we have a root level logger set up already:
https://github.com/pulumi/pulumi-terraform-bridge/blob/83e6003e13db091a349b607302932da41f057c23/pkg/tfbridge/provider.go#L211

This makes the method necessary only when there is a URN to specify.

**Comment by t0yv0** [comment]
But this will specialize it to the URN (now known) which will improve log locality no?

**Comment by iwahbe** [comment]
> But this will specialize it to the URN (now known) which will improve log locality no?

In the case of custom providers yes.

**Comment by t0yv0** [comment]
ah yes, explicit providers. well then perhaps not as important. Anyway it went in so that's OK with me.

**Pull request merged**
