### PR TITLE
Revert "Allow the `Type` override to effect downstream types"

### PR DESCRIPTION
**Pull request by t0yv0**
Reverts pulumi/pulumi-terraform-bridge#1550

Discovered that ExtraTypes support is broken by this change per https://github.com/pulumi/pulumi-terraform-bridge/issues/1626

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
I agree with the revert to unblock talos and oci. That said, `ExtraTypes` isn't the only thing wrong here. pulumi-oci is blocked on the same [error message](https://github.com/pulumi/pulumi-oci/actions/runs/7550497575/job/20556231046), but it doesn't specify `ExtraTypes`.

**Comment by t0yv0** [comment]
Can you please capture everything relevant in the tracker. Appreciated.

**Comment by iwahbe** [comment]
> Can you please capture everything relevant in the tracker. Appreciated.
> 
> As far as I can see OCI built on [pulumi/pulumi-oci#327](https://github.com/pulumi/pulumi-oci/pull/327) without an issue.

The current OCI version builds correctly, but the [new OCI version](https://github.com/pulumi/pulumi-oci/issues/325) [does not](https://github.com/pulumi/pulumi-oci/actions/runs/7550497575).


Screenshot 2024-01-18 at 12 36 10 PM

**Comment by t0yv0** [comment]
OK I captured this in 1626 for now, we can split later on if it turns out a different issue. Thanks! Friendly reminder we need to track things..

**Pull request merged**
