### PR TITLE
Add install tf GHA step

### PR DESCRIPTION
**Pull request by VenelinMartinov**

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
This is hitting a windows specific issue with the Engine/Automation API = (

**Comment by iwahbe** [comment]
Awaiting a windows installation fix in pulumi/pulumi.

@VenelinMartinov will file an issue and link it here.

**Comment by VenelinMartinov** [comment]
Blocked on https://github.com/pulumi/pulumi/issues/16414

**Comment by VenelinMartinov** [comment]
The issue above has instructions on a workaround

**Comment by VenelinMartinov** [comment]
Opened https://github.com/pulumi/pulumi-terraform-bridge/issues/2221 for fixing this

**Comment by iwahbe** [comment]
It seems like this is blocked and the PR is getting pretty out of date. @VenelinMartinov Is it worth writing up the progress made on the original issue and then closing?

**Pull request closed without merging**
