### PR TITLE
Ensure a deterministic diff result

### LINKED ISSUE #876: Diff.response.stables is returned in a non-deterministic order
### What happened?

I was writing https://github.com/pulumi/pulumi-hcloud/pull/173/commits/bf53915ee42b2955272d00eba30272c2ad0beb97, and I noticed that I needed to escape `stables` (with `"*"`) because it changed from run to run.

### Expected Behavior

Diff is fully determistic.

### Steps to reproduce

Remove `"*"` from my test. Observe that the failure changes over time.

### Output of `pulumi about`

NA

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #876

This prevented https://github.com/pulumi/pulumi-gcp/pull/1785 from merging.

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
"But people might start depending on the order!"
Thanks for fixing - I've had to escape a few diffs in GRPC tests with "*" as well

**Comment by VenelinMartinov** [comment]
Actually could this have any serious performance implications?

**Comment by iwahbe** [comment]
> Actually could this have any serious performance implications?

I'd be very surprised if the number of properties being sorted were large enough to have performance implications. Especially compared to the overhead of serialization, IPC, and network requests.

**Comment by t0yv0** [comment]
Probably fine, can't think of why the ordering would matter in prod, but might trip up some overfitting tests. A bit odd to change prod code to make testing easier. But I can see the motivation.

**Pull request merged**
