### PR TITLE
Fix Set diffing to exclude items whose values are unchanged

### PR DESCRIPTION
**Pull request by komalali**
`tfDiff` includes each item of the set, even when that specific item hasn't changed (i.e. d.Old == d.New). So if we just check for and exclude those cases, we get the results we expect.

Fixes: #296

### CODE REVIEW

**Comment by pgavlin** [comment]
> DiffKind is Update for a set item when there is actually no diff

Can you elaborate on this? Do we understand exactly the circumstances under which this occurs?

**Comment by komalali** [comment]
@pgavlin Thanks for asking that question, it helped me figure out the last remaining piece of the puzzle. It turns out that tfDiff includes each item of the set, even when that specific item hasn't changed (i.e. d.Old == d.New). So if we just check for and exclude those cases, we get the results we expect.

**Comment by komalali** [comment]
Actually, I think we don't need joe's fix at all. If we are just excluding the diffs where `d.Old == d.New` we don't ever end up in a situation where the paths get overwritten.

**Review by pgavlin — APPROVED** [review]
🎉

**Comment by joeduffy** [comment]
Woohoo, so glad this ended up being even simpler!

**Pull request merged**
