### PR TITLE
Add a test for tfbridge.SchemaInfo.NestedType

### PR DESCRIPTION
**Pull request by iwahbe**
Motivated by https://github.com/pulumi/pulumi-terraform-bridge/issues/2637

Concerningly, it looks like `.NestedType` wasn't under test before.

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
Tests 👏

**Comment by VenelinMartinov** [comment]
I am a bit confused as to why the test passes? Shouldn't it fail according to your comment in https://github.com/pulumi/pulumi-terraform-bridge/issues/2637?

**Comment by iwahbe** [comment]
> I am a bit confused as to why the test passes. Shouldn't it fail according to your comment in #2637?

I was surprised that they pass too. Investigation showed that `.NestedType` is applied later.

**Comment by iwahbe** [comment]
> Should we also add a test which captures the failure in #2637?

I think the failure there is more communication then technical. I need to touch base with @zbuchheit, but I think the problem there is I was reading properties as **property names** and @zbuchheit meant **property types**.

**Pull request merged**
