### PR TITLE
Mark old modules as deprecated

### PR DESCRIPTION
**Pull request by blampe**
This should only be merged well after our automated upgrades have
pointed downstream providers at the new import paths.

Update 2024-11-08

These modules are no longer used internally and can be marked deprecated:
* [github.com/pulumi/pulumi-terraform-bridge/pf](https://github.com/search?q=org%3Apulumi+path%3Ago.mod+%22github.com%2Fpulumi%2Fpulumi-terraform-bridge%2Fpf+%22&type=code)
* [github.com/pulumi/pulumi-terraform-bridge/testing](https://github.com/search?q=org%3Apulumi+path%3Ago.mod+%22github.com%2Fpulumi%2Fpulumi-terraform-bridge%2Ftesting+%22&type=code)
* [github.com/pulumi/pulumi-terraform-bridge/x/muxer](https://github.com/search?q=org%3Apulumi+path%3Ago.mod+%22github.com%2Fpulumi%2Fpulumi-terraform-bridge%2Fx%2Fmuxer+%22&type=code)

### CODE REVIEW

**Comment by blampe** [comment]
This change is part of the following stack:

- #2473
    - #2477
        - #2480
            - #2482 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Comment by iwahbe** [comment]
@blampe Can you point me to the automation that will move our providers over to the new module path?

**Comment by blampe** [comment]
@iwahbe https://github.com/pulumi/ci-mgmt/pull/1103

**Comment by blampe** [comment]
@iwahbe @t0yv0 the migration has rolled out to all providers so we should be OK to mark these as deprecated now. There are links in the PR description showing these are no longer directly consumed.

**Review by iwahbe — APPROVED** [review]
LGTM.

Nit: you can deprecate at the module level.

**Comment by t0yv0** [comment]
Nice!!

**Pull request merged**
