### PR TITLE
Make pf data source map mutable

### PR DESCRIPTION
**Pull request by VenelinMartinov**
This change makes the PF datasources map mutable in order to support aliases like we do for resources.

The changes here mimic what we did for resources in https://github.com/pulumi/pulumi-terraform-bridge/pull/1938

Related to https://github.com/pulumi/pulumi-terraform-bridge/issues/2585

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
This change is part of the following stack:

- #2615
    - #2616 ◀
        - #2617

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Review by iwahbe — APPROVED** [review]
This looks fine as long as we don't cast out of `newSchemaOnlyDataSourceMap(...)`.  We are just casting away information.

**Comment by VenelinMartinov** [comment]
>This looks fine as long as we don't cast out of newSchemaOnlyDataSourceMap(...). We are just casting away information.

What do you mean here? Which cast are you referring to?

**Comment by iwahbe** [comment]
> > This looks fine as long as we don't cast out of newSchemaOnlyDataSourceMap(...). We are just casting away information.
> 
> What do you mean here? Which cast are you referring to?

`newSchemaOnlyDataSourceMap` discards information going from `runtypes.DataSources` to `shim.ResourceMap`. That's what I meant.

**Pull request merged**
