### PR TITLE
Avoid setting conflicting default values

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Changes to fix https://github.com/pulumi/pulumi/issues/3621

The problem is that TF schema can have two fields that conflict with each other and both have default values. In this case, the old code sets defaults for both fields, and TF complains about the conflict.

I exclude both conflicting values, as setting just one might lead to non-deterministic behavior (we don't order the iteration of fields).

My solution is probably not bullet-proof: there are some logic branches that would lead to conflicting values (e.g. something with old values). The full solution might involve another stage when we first collect all possible defaults and conflicting fields, and then calculate all conflicts and exclude them, but this sounds complicated.

### CODE REVIEW

**Comment by pgavlin** [comment]
> The problem is that TF schema can have two fields that conflict with each other and both have default values. In this case, the old code sets defaults for both fields, and TF complains about the conflict.

How does TF handle this situation?

**Comment by pgavlin** [comment]
(i.e. if you try to `terraform plan` a resource that has such a schema, what happens?)

**Comment by mikhailshilkov** [comment]
@pgavlin This works fine (no values for conflicting fields):

```
resource "azurerm_subnet" "example" {
  name                 = "testsubnet"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.1.0/24"
}
```

this also works (one value):

```
resource "azurerm_subnet" "example" {
  name                 = "testsubnet"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.1.0/24"
  enforce_private_link_endpoint_network_policies = false
}
```

this fails with the coflict (even though values equal to default):

```
resource "azurerm_subnet" "example" {
  name                 = "testsubnet"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.1.0/24"
  enforce_private_link_endpoint_network_policies = false
  enforce_private_link_service_network_policies = false
}
```

**Comment by pgavlin** [comment]
> @pgavlin This works fine (no values for conflicting fields):
> 
> ```
> resource "azurerm_subnet" "example" {
>   name                 = "testsubnet"
>   resource_group_name  = "${azurerm_resource_group.test.name}"
>   virtual_network_name = "${azurerm_virtual_network.test.name}"
>   address_prefix       = "10.0.1.0/24"
> }
> ```

What ends up in the state file?

**Comment by mikhailshilkov** [comment]
> What ends up in the state file?

```
            "enforce_private_link_endpoint_network_policies": false,
            "enforce_private_link_service_network_policies": false,
````

**Comment by pgavlin** [comment]
Okay. What does the Pulumi state look like for this resource if no value is set for either field? Does it also contain the `false/false` states like TF?

**Comment by mikhailshilkov** [comment]
> What does the Pulumi state look like for this resource if no value is set for either field? Does it also contain the false/false states like TF?

With the current version, Pulumi can't get through preview because of the conflict error. After the PR,  these fields are not in the state (only in outputs, both = false).

**Comment by pgavlin** [comment]
> (only in outputs, both = false).

Perfect.

**Pull request merged**
