### PR TITLE
Docs Readability: Newlines in Import sections

### PR DESCRIPTION
**Pull request by guineveresaenger**
This PR allows docsgen to retain newlines in import sections by adding a double newline placeholder to the end of every line in the `Import` section of the docs.

Previously, newlines were not honored except around the import code part itself.

Tests are adjusted to reflect newlines being appended rather than prepended.

[Here is a registry preview](http://registry--origin-pr-3897-6eedfa57.s3-website.us-west-2.amazonaws.com/registry/packages/gcp/api-docs/certificatemanager/certificatemap/)

Screenshot from that preview:

Screenshot 2024-02-02 at 5 33 14 PM

Closes https://github.com/pulumi/pulumi-gcp/issues/1375.

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
Looks good! Might be nice to add one of the broken motivating examples as a test!

**Review by iwahbe — APPROVED** [review]
The GCP imports look much better. 2 things to address before merging:

- I agree with @VenelinMartinov. Let's make sure we add a regression test for gcp-style imports.

- If you haven't done this already, lets make sure this doesn't break imports for aws and azure.

**Comment by guineveresaenger** [comment]
This change will add extra newlines to import sections of resource descriptions across the board. It should not affect how they are displayed.

A test of AWS registry docs is [building here](https://github.com/pulumi/registry/pull/3905)

**Comment by guineveresaenger** [comment]
No diff in display on docs preview on AWS import instructions, see before/after screenshots. Given the ✅ here and improved rendering for GCP, I am going to merge.

Screenshot 2024-02-05 at 10 47 18 AM
Screenshot 2024-02-05 at 10 47 12 AM

**Pull request merged**
