### PR TITLE
Remove InstanceStateStrategy

### PR DESCRIPTION
**Pull request by iwahbe**
A [search](https://github.com/search?q=org%3Apulumi%20InstanceStateStrategy&type=code) shows that `InstanceStateStrategy` isn't being used, so we can safely remove it.

This simplifies our code.

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
Thank you!

**Comment by iwahbe** [comment]
@t0yv0 This is failing one test:
```
=== RUN   TestRegressAws1423
=== RUN   TestRegressAws1423/testCase1
=== RUN   TestRegressAws1423/testCase2/createPreview
=== RUN   TestRegressAws1423/testCase2/diff
    json_match.go:149: 
        	Error Trace:	/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/json_match.go:149
        	            				/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/json_match.go:80
        	            				/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/json_match.go:133
        	            				/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/json_match.go:145
        	            				/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/json_match.go:45
        	            				/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/replay.go:198
        	            				/Users/ianwahbe/go/pkg/mod/github.com/pulumi/providertest@v0.0.11/replay/replay.go:121
        	            				/Users/ianwahbe/go/src/github.com/pulumi/pulumi-terraform-bridge/pkg/tests/regress_aws_1423_test.go:442
        	Error:      	Not equal: 
        	            	expected: "\"DIFF_NONE\""
        	            	actual  : "\"DIFF_SOME\""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-"DIFF_NONE"
        	            	+"DIFF_SOME"
        	Test:       	TestRegressAws1423/testCase2/diff
        	Messages:   	at #["changes"]
    json_match.go:135: [#["detailedDiff"]] unexpected value {
          "rules[0].name": {
            "kind": "UPDATE"
          },
          "rules[0].priority": {
            "kind": "UPDATE"
          },
          "rules[0].statement.geoMatchStatement.countryCodes[0]": {
            "kind": "UPDATE"
          },
          "rules[0].visibilityConfig.cloudwatchMetricsEnabled": {
            "kind": "UPDATE"
          },
          "rules[0].visibilityConfig.metricName": {
            "kind": "UPDATE"
          },
          "rules[0].visibilityConfig.sampledRequestsEnabled": {
            "kind": "UPDATE"
          }
        }
    json_match.go:135: [#["diffs"]] unexpected value [
          "rules",
          "rules",
          "rules",
          "rules",
          "rules",
          "rules"
        ]
--- FAIL: TestRegressAws1423 (0.54s)
    --- PASS: TestRegressAws1423/testCase1 (0.16s)
    --- PASS: TestRegressAws1423/testCase2/createPreview (0.16s)
    --- FAIL: TestRegressAws1423/testCase2/diff (0.21s)
```

Should I just remove this test, since it is testing behavior that is not actually used, or is this a sign that something is wrong with `shimv2.WithPlanResourceChange`?

**Comment by t0yv0** [comment]
Yeah amenable to removing this test, or you an do `detailedDiff:"*"` and `diffs:"*"`.

**Comment by iwahbe** [comment]
> Yeah amenable to removing this test, or you an do `detailedDiff:"*"` and `diffs:"*"`.

I'm just going to remove. Setting `"detailedDiff":"*"` and `"diffs":"*"` wouldn't do it, since we would also need to set `"changes":"*"` at which point why bother keeping the test.

**Pull request merged**
