### PR TITLE
Restore CI

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1335

### CODE REVIEW

**Comment by t0yv0** [comment]
Do we know what the cause of  FAIL: TestBasicProgram (16.30s) is? Is there a workaround?

**Comment by iwahbe** [comment]
> Do we know what the cause of FAIL: TestBasicProgram (16.30s) is? Is there a workaround?

We test against the latest install of the pulumi binary, and it hit https://github.com/pulumi/pulumi-yaml/issues/489. The workaround is to skip the test or wait for a good release (which has happened).

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/1337

**Comment by t0yv0** [comment]
🚢 we'll pin later.

**Comment by iwahbe** [comment]
I raised https://github.com/pulumi/pulumi-yaml/issues/492 for after the break.

**Pull request merged**
