### PR TITLE
Remove vendored plugin server

### PR DESCRIPTION
**Pull request by iwahbe**
As part of #2148, this PR removes the duplicate implementation of `pulumigrpc.ResourceProviderServer` copied over from pulumi/pulumi and then modified.

This is a post #2258 version of #2195, and is much less invasive.

Addressing previous edits in response to
https://github.com/pulumi/pulumi-terraform-bridge/pull/2195#issuecomment-2243872704:

- #1716: This change accommodated for a previous edit (`ProviderWithContext`) and is no longer necessary. That said, the tests it introduced are still present (and continue to pass), so we are sure this commit did not break the functionality.
- #1683: Simply brings DiffConfig into line with pu/pu, which we get for free by not vendoring. It is also under test.
- #1047: This is still handled in `provider_server.go`, and is still under test.
- #1065: This has already been moved out of this area in #2258, so it is no longer relevant here.

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
LGTM - would be good to test with a PF provider and/or a dynamically bridged one

**Comment by VenelinMartinov** [comment]
You've hit https://github.com/pulumi/pulumi/issues/14240

**Comment by iwahbe** [comment]
I'm opening up test PRs in [gcp](https://github.com/pulumi/pulumi-gcp/pull/2377) and [random](https://github.com/pulumi/pulumi-random/pull/1175). If work as expected, then I'll merge.

Dynamic bridged providers layer on top of PF, so I don't think they need explicit testing.

**Comment by t0yv0** [comment]
Very nice cleanup here thank you.

**Pull request merged**
