### PR TITLE
Initial setup for cross-testing bridged providers against TF-defined behavior 

### PR DESCRIPTION
**Pull request by t0yv0**
Tests to compare and contrast the behavior of a given Terraform provider under Terraform CLI against the behavior of the
same provider bridged to Pulumi and used under Pulumi CLI.

### CODE REVIEW

**Comment by t0yv0** [comment]
These tests can pass now on v3.111.1 of Pulumi CLI without requiring customized pulumi-yaml and pulumi CLI builds - CC @VenelinMartinov 

Looks like we need to upgrade the bridge to latest, and I need to tidy up the PRs here to get them mergeable then we can land an initial version of this and iterate further.

**Comment by VenelinMartinov** [comment]
FYI I had a go at implementing a cross-test on top of this for https://github.com/pulumi/pulumi-terraform-bridge/issues/1767:
https://github.com/pulumi/pulumi-terraform-bridge/pull/1768

Didn't quite work but it looks promising.

**Comment by VenelinMartinov** [comment]
I tried to run this earlier today and hit this issue:
```
Diagnostics:
          pulumi:pulumi:Stack (project-test):
            Error: error resolving type of resource example: internal error loading package "crossprovider": could not find latest version for provider crossprovider: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-crossprovider/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
              on Pulumi.yaml line 92:
              92:         type: crossprovider:index:TestRes
```
I was certainly able to run this before. Is this an issue with my local setup or a regression in the PR?

**Comment by t0yv0** [comment]
Upgrade your Pulumi CLI on latest.

Looks like these tests fail on some OS-s because TF CLI is not setup in CI. I'll just disable them conditionally on O.S. for now to run only on Linux.

**Review by VenelinMartinov — APPROVED** [review]
🔥

**Pull request merged**
