### PR TITLE
fix: do not create an empty `__defaults` entry

### LINKED ISSUE #2189: Importing PluginFramework based resources generates extraneous __defaults
### What happened?

The gory details are in https://github.com/pulumi/pulumi-aws/issues/4204

It looks like PF resources should not be injecting __defaults during import as they do not support it, but it might be happening through an unintended side-effect of code reuse. 

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by corymhall**
PF resources should not be injecting __defaults during
import as they do not support it, but it is happening through an
unintended side-effect of code reuse from `sdkv2`.

I could think of a couple other ways to handle this:
1. Do some post processing on the `pf` side to remove `__defaults`
2. Duplicate the code in the `pf` and remove the code specific to
   injecting `__defaults`

I opted for just removing where we inject an empty `__defaults`. Any
code that references `__defaults` should handle the case where
`__defaults` does not exist.

fixes #2189, fixes https://github.com/pulumi/pulumi-aws/issues/4204

### CODE REVIEW

**Review by iwahbe — COMMENTED** [review]
This should be fine... The only place this looks concerning is in [`nameRequiresDeleteBeforeReplace`](https://github.com/pulumi/pulumi-terraform/pull/465), where we seem to use the existence of `__defaults` as an indicator for old resources.

https://github.com/pulumi/pulumi-terraform-bridge/blob/5f7b9b60a4d84802253908d7d5b385f3142a962f/pkg/tfbridge/schema.go#L197-L208

I think we will need a migration path that doesn't break `nameRequiresDeleteBeforeReplace` before merging. The first step will be to add tests that cover `nameRequiresDeleteBeforeReplace`. Then we can either:

1. Come up with a new mechanism for `nameRequiresDeleteBeforeReplace` to detect old resources.
2. Argue (ideally by looking at our state files) that we can safely assume that every resource has a `__defaults` block and we can get by without the `hasDefaults` check.

**Comment by corymhall** [comment]
@iwahbe 

> I think we will need a migration path that doesn't break `nameRequiresDeleteBeforeReplace` before merging.

This PR only removes the empty defaultsKey (i.e. `"__defaults": []`). It looks like `nameRequiresDeleteBeforeReplace` only cares about `__defaults` as long as it actually has a value. My PR doesn't prevent the bridge from setting `__defaults` elsewhere with actual values.

https://github.com/pulumi/pulumi-terraform-bridge/blob/95499441512f26910ccdc4ba3b176a78357d067f/pkg/tfbridge/schema.go#L210-L216

We do have existing tests around `DeleteBeforeReplace` that I didn't touch and are still passing
https://github.com/pulumi/pulumi-terraform-bridge/blob/95499441512f26910ccdc4ba3b176a78357d067f/pkg/tfbridge/schema_test.go#L2380-L2380

**Comment by iwahbe** [comment]
@corymhall That is mostly, but not entirely true. AFAIK, you are arguing that this change is a no-op:

<details>
<summary> patch </summary>

```patch
 pkg/tfbridge/schema.go | 17 ++++++-----------
 1 file changed, 6 insertions(+), 11 deletions(-)

diff --git a/pkg/tfbridge/schema.go b/pkg/tfbridge/schema.go
index f3849dda..d0ed08bd 100644
--- a/pkg/tfbridge/schema.go
+++ b/pkg/tfbridge/schema.go
@@ -200,19 +200,14 @@ func nameRequiresDeleteBeforeReplace(news resource.PropertyMap, olds resource.Pr
 	tfs shim.SchemaMap, resourceInfo *ResourceInfo) bool {
 	fields := resourceInfo.Fields
 
-	defaults, hasDefaults := news[defaultsKey]
-	if !hasDefaults || !defaults.IsArray() {
-		// If there is no list of properties that were populated using defaults, consider the resource autonamed.
-		// This avoids setting delete-before-replace for resources that were created before the defaults list existed.
-		return false
-	}
-
 	hasDefault := map[resource.PropertyKey]bool{}
-	for _, key := range defaults.ArrayValue() {
-		if !key.IsString() {
-			continue
+	if defaults, hasDefaults := news[defaultsKey]; hasDefaults && defaults.IsArray() {
+		for _, key := range defaults.ArrayValue() {
+			if !key.IsString() {
+				continue
+			}
+			hasDefault[resource.PropertyKey(key.StringValue())] = true
 		}
-		hasDefault[resource.PropertyKey(key.StringValue())] = true
 	}
 
 	// These are a list of Pulumi named fields that we care about comparing to try
```

</details>

If `UniqueNameFields` is non-empty with a key that hasn't changed and no default, the returned value would be `true` (previously it would be false). `UniqueNameFields` is only used on one resource in GCP, so it might not be worth worrying over as long as GCP passes tests on the new version.

As I understand this block:

```go
	for key := range news {
		_, _, psi := getInfoFromPulumiName(key, tfs, fields)
		if psi != nil && psi.HasDefault() && psi.Default.AutoNamed && !hasDefault[key] {
			return true
		}
	}
```

If there is a key in news where the default wasn't applied (because it was set) but there is a default that could have been applied, `true` is returned, previously `false` would have been returned.

I think this is safe if and only if `psi.HasDefault()` implies `key` is a member of `hasDefault`.

**Comment by VenelinMartinov** [comment]
Doesn't https://github.com/pulumi/pulumi-terraform-bridge/blob/da2282374d3b7fb2227e526d2ecede9db7b8c03b/pkg/tfbridge/schema.go#L944 also possibly set an empty defaults value?

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/931 UniqueNameFields is a feature that I'd love to sunset.

**Comment by t0yv0** [comment]
This is a big detour, you might be better off extending https://github.com/pulumi/pulumi-terraform-bridge/blob/t0yv0%2Fdocument-sets/pf/tfbridge/provider_read.go#L93 to cover nested locations.

**Comment by corymhall** [comment]
Closing in favor of #2243

**Pull request closed without merging**
