### PR TITLE
Try to tag the right person on bridge upgrade PRs

### PR DESCRIPTION
**Pull request by VenelinMartinov**
It's what we do in https://github.com/pulumi/pulumi-terraform-bridge/blob/4739ea0598a543ffa62cfb3641a2782309bbe93c/.github/workflows/update-providers-test.yml#L55 and that seems to work.

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Seems to work:
https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/7747439170/job/21127905599
`"pr-reviewers": "VenelinMartinov",`

https://github.com/pulumi/pulumi-hcloud/actions/runs/7747441598/job/21127911044

https://github.com/pulumi/pulumi-hcloud/pull/402

**Comment by VenelinMartinov** [comment]
I think this only worked in my test because of the hacks - when auto triggered it probably doesn't have a triggering_actor.

We need something else here.

**Comment by iwahbe** [comment]
When auto-triggering it must have a `github.actor`, since that seems like where GH inherits the PRs permissions from. The actor might be @pulumi-bot, but it could also be the person who tagged the release.

**Comment by VenelinMartinov** [comment]
Ok, I think this should work. In https://github.com/pulumi/pulumi-terraform-bridge/pull/1668/commits/bb1d7d2a6a663b117ec9c3642fb4dea9e2849793 i made it trigger on ANY push, which should have the same payload as when we push a tag, so this should be fine!

I'll add special case for pulumi-bot

**Comment by iwahbe** [comment]
This is related to #1670.

**Comment by VenelinMartinov** [comment]
@t0yv0 I've replaced you as the default reviewer, LMK if you'd like me to revert that.

**Pull request merged**
